# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

###

# curl 'http://localhost:8080/SwethaBookstoreOrder/api/orders'
#  -H 'Accept: */*'
#  -H 'Accept-Language: en-US,en;q=0.9'
#  -H 'Cache-Control: max-age=0'
#  -H 'Connection: keep-alive'
#  -H 'Content-Type: application/json'
#  -H 'Origin: http://localhost:5173'
#  -H 'Referer: http://localhost:5173/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-site'
#  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36'
#  -H 'sec-ch-ua: "Google Chrome";v="111", "Not(A:Brand";v="8", "Chromium";v="111"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "macOS"'
#  --data-raw '{"cart":{"itemArray":[{"book":{"bookId":1003,"title":"Reminders of Him","author":"Collen Hoover","description":"","price":653,"rating":0,"isPublic":false,"isFeatured":false,"categoryId":1001},"quantity":1},{"book":{"bookId":1004,"title":"Heart Bones","author":"Collen Hoover","description":"","price":899,"rating":0,"isPublic":true,"isFeatured":false,"categoryId":1001},"quantity":1},{"book":{"bookId":1008,"title":"Just by Looking at Him","author":"Ryan O Connell","description":"","price":3899,"rating":0,"isPublic":true,"isFeatured":false,"categoryId":1002},"quantity":3},{"book":{"bookId":1006,"title":"The Reality Meltdown","author":"Dan Cray","description":"","price":3019,"rating":0,"isPublic":false,"isFeatured":false,"categoryId":1002},"quantity":1}]},"customerForm":{"name":"Swetha","address":"kjsnxijsxnijsnxj","phone":"9283389834","email":"srswetharajeevp@gmail.com","ccNumber":"4444333322221111","ccExpiryMonth":4,"ccExpiryYear":2023}}'
#  --compressed
###

# curl 'http://localhost:8080/SwethaBookstoreOrder/api/orders'
#  -H 'Accept: */*'
#  -H 'Accept-Language: en-US,en;q=0.9'
#  -H 'Cache-Control: max-age=0'
#  -H 'Connection: keep-alive'
#  -H 'Content-Type: application/json'
#  -H 'Origin: http://localhost:5173'
#  -H 'Referer: http://localhost:5173/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-site'
#  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36'
#  -H 'sec-ch-ua: "Google Chrome";v="111", "Not(A:Brand";v="8", "Chromium";v="111"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "macOS"'
#  --data-raw '{"cart":{"itemArray":[{"book":{"bookId":1003,"title":"Reminders of Him","author":"Collen Hoover","description":"","price":653,"rating":0,"isPublic":false,"isFeatured":false,"categoryId":1001},"quantity":1},{"book":{"bookId":1004,"title":"Heart Bones","author":"Collen Hoover","description":"","price":899,"rating":0,"isPublic":true,"isFeatured":false,"categoryId":1001},"quantity":1},{"book":{"bookId":1008,"title":"Just by Looking at Him","author":"Ryan O Connell","description":"","price":3899,"rating":0,"isPublic":true,"isFeatured":false,"categoryId":1002},"quantity":3},{"book":{"bookId":1006,"title":"The Reality Meltdown","author":"Dan Cray","description":"","price":3019,"rating":0,"isPublic":false,"isFeatured":false,"categoryId":1002},"quantity":1}]},"customerForm":{"name":"Swetha","address":"nwkjdnwjdnwdkj","phone":"5713387709","email":"rswetha@vt.edu","ccNumber":"4444333322221111","ccExpiryMonth":2,"ccExpiryYear":2023}}'
#  --compressed
###

# curl 'http://localhost:8080/SwethaBookstoreOrder/api/orders'
#  -H 'Accept: */*'
#  -H 'Accept-Language: en-US,en;q=0.9'
#  -H 'Cache-Control: max-age=0'
#  -H 'Connection: keep-alive'
#  -H 'Content-Type: application/json'
#  -H 'Origin: http://localhost:8080'
#  -H 'Referer: http://localhost:8080/SwethaBookstoreOrder/checkout/client'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-origin'
#  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36'
#  -H 'sec-ch-ua: "Google Chrome";v="111", "Not(A:Brand";v="8", "Chromium";v="111"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "macOS"'
#  --data-raw '{"cart":{"itemArray":[{"book":{"bookId":1003,"title":"Reminders of Him","author":"Collen Hoover","description":"","price":653,"rating":0,"isPublic":false,"isFeatured":false,"categoryId":1001},"quantity":1},{"book":{"bookId":1002,"title":"Verity","author":"Collen Hoover","description":"","price":529,"rating":0,"isPublic":false,"isFeatured":true,"categoryId":1001},"quantity":1}]},"customerForm":{"name":"Swetha","address":"nwkjdnwjdnwdkj","phone":"5713387709","email":"srswetharajeevp@gmail.com","ccNumber":"4444333322221111","ccExpiryMonth":4,"ccExpiryYear":2023}}'
#  --compressed
POST http://localhost:8080/SwethaBookstoreOrder/api/orders
Accept: */*
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Connection: keep-alive
Origin: http://localhost:8080
Referer: http://localhost:8080/SwethaBookstoreOrder/checkout/client
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
sec-ch-ua: "Google Chrome";v="111", "Not(A:Brand";v="8", "Chromium";v="111"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
Content-Type: application/json

{
  "cart": {
    "itemArray": [
      {
        "book": {
          "bookId": 1003,
          "title": "Reminders of Him",
          "author": "Collen Hoover",
          "description": "",
          "price": 653,
          "rating": 0,
          "isPublic": false,
          "isFeatured": false,
          "categoryId": 1001
        },
        "quantity": 1
      },
      {
        "book": {
          "bookId": 1002,
          "title": "Verity",
          "author": "Collen Hoover",
          "description": "",
          "price": 529,
          "rating": 0,
          "isPublic": false,
          "isFeatured": true,
          "categoryId": 1001
        },
        "quantity": 1
      }
    ]
  },
  "customerForm": {
    "name": "Swe",
    "address": "nwkjdnwjdnwdkj",
    "phone": "5713387709",
    "email": "srswetharajeevp@gmail.com",
    "ccNumber": "4444333322211",
    "ccExpiryMonth": 4,
    "ccExpiryYear": 2023
  }
}

###


###



###


###
